### ISSUE TITLE
Add support for charts

### ISSUE THREAD

**Issue by Stephanevg** [Stephanevg/PSHTML#150]
The following issues must be all completed before we can officially support Charts:

- [X] Support for BarCharts (#149 )
- [x] Support for DoughnutCharts (#148)
- [x] Support for PieCharts (#147 )
- [X] Support for LineCharts (#146 )
- [X] All pester tests must pass on Windows
![image](https://user-images.githubusercontent.com/6302961/50735707-58e91800-11b3-11e9-84f6-7b23ce1f4f48.png)
- [x] All pester tests must pass on Linux (https://github.com/Stephanevg/PSHTML/issues/162)

**Comment by Stephanevg** [comment]
Done. See following PR's:
Feature_Charts to Dev --> https://github.com/Stephanevg/PSHTML/pull/168 
Dev to Master --> https://github.com/Stephanevg/PSHTML/pull/161
